FROM node:20-alpine3.16
WORKDIR /app
EXPOSE 80

ARG DB_NAME
ARG ALLOWED_ORIGINS
ARG DATABASE_URL
ARG TOKEN_KEY
ARG COOKIE_KEY
ARG COOKIE_PARSER_KEY


ENV SERVER_PORT=80
ENV APP_ROUTE='/pms/v1'
ENV APP_NAME='Product Manager Service'
ENV TOKEN_HEADER_KEY='authorization'
ENV TOKEN_EXPIRATION_TIME='30m'
ENV REFRESH_TOKEN_EXPIRATION_TIME='5h'

ENV DB_NAME ${DB_NAME}
ENV DATABASE_URL ${DATABASE_URL}
ENV ALLOWED_ORIGINS ${ALLOWED_ORIGINS}
ENV TOKEN_KEY ${TOKEN_KEY}
ENV COOKIE_KEY ${COOKIE_KEY}
ENV COOKIE_PARSER_KEY ${COOKIE_PARSER_KEY}

COPY . /app

CMD ["yarn", "start"]
